import '@/styles/global.scss'
import { LayoutProps } from '@/types/layout'
import Header from '@/components/Header'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = ({ children }: LayoutProps) => {
	return (
		<div>
			<Header />
			{
				children
			}
		</div>
	)
}

export default RootLayout	
